### ISSUE TITLE
No icons for templates

### ISSUE THREAD

**Issue by jonchampagne** [Weilbyte/PVEDiscordDark#1]
Templates do not have their own icon. They use the default icon with the white background. Installed via the installer script.

Templates with the bad looking white icons:
![image](https://user-images.githubusercontent.com/1485633/53657786-1f69e180-3c25-11e9-9885-8b7fb9ed40db.png)

**Comment by Weilbyte** [comment]
Uh oh! Thanks, I'll fix this by tomorrow.

**Comment by Weilbyte** [comment]
Where do you find these in the UI? My templates don't have those icons

**Comment by jonchampagne** [comment]
On a VM, I go to "More" in the top right, and select "Convert to template." Once it's a template, I need to refresh the page for it to use the new incorrect icon.

**Comment by Weilbyte** [comment]
Fixed
