### ISSUE TITLE
Could we have one for 7.1 please

### ISSUE THREAD

**Issue by Vik-Geerawor** [Weilbyte/PVEDiscordDark#100]
Doesn't work for 7.1, grateful if you could provide an updated version please. Thanks a mil..!

**Comment by Nerdtality** [comment]
This works just fine in 7.1

**Comment by Nerdtality** [comment]
`wget https://raw.githubusercontent.com/Weilbyte/PVEDiscordDark/master/PVEDiscordDark.sh`
`chmod +X PVEDiscordDark.sh`
`bash PVEDiscordDark.sh install`

**Comment by Vik-Geerawor** [comment]
Not sure why it doesn't seem to work for me. Thanks anyways.

![ProxmoxDarkTheme](https://user-images.githubusercontent.com/37639359/144421084-268d5a53-e5a5-419d-9b2f-10f0953def40.jpg)

**Comment by apcorton** [comment]
@Vik-Geerawor try clearing your browser cache with Ctrl-Shift-R or try using the installer again

**Comment by Vik-Geerawor** [comment]
@apcorton - Thanks a mil..! Clearing the browser cache fixed it. Thank you both :)

**Comment by Nerdtality** [comment]
Glad to hear you got it working.

**Comment by Weilbyte** [comment]
7.1 works, just need to finish some things before I add it to the supported list so the warning in the CLI goes away.

**Comment by apcorton** [comment]
> 

Keep up the good work - appreciate your service

**Comment by eins** [comment]
@Vik-Geerawor was the issue an old browser cache ?
which browser are you using ?

**Comment by Weilbyte** [comment]
Will be added to supported list on Friday.

**Comment by Vik-Geerawor** [comment]
> @Vik-Geerawor was the issue an old browser cache ? which browser are you using ?
Hi @eins,

I'm using the latest Google Chrome:
![image](https://user-images.githubusercontent.com/37639359/147067524-7cb4ccb4-6fa0-4a28-9b4a-a45a5e89875f.png)
