### ISSUE TITLE
Offline Bundle?

### ISSUE THREAD

**Issue by erasedhammer99** [Weilbyte/PVEDiscordDark#107]
I run proxmox disconnected from the internet, and I know the script needs internet access intially to install. It appears it periodically reconnects to the internet, and if I can't, it reverts back to light mode. 

Would it be possible to get a version of this script that operates entirely offline?

**Comment by Weilbyte** [comment]
Internet is only required during install. It should not be trying to periodically reconnect after, as all the image assets are downloaded locally. Can you double-check that browser cache was cleared?

**Comment by erasedhammer99** [comment]
Hmm, strange it must be something proxmox related (definitely not APT, I run a local proxy for that). It came from logs in my firewall. (destination: 104.21.66.227,172.67.208.182,144.217.225.162)

I just assumed it was your script, as around the same time the gui also reverted back to light mode (no reboot, just apt upgrade). 

Regardless, would it be possible to have an offline installer?

**Comment by RisedSky** [comment]
If you do a `apt upgrade`, the dark mode will be reverted by Proxmox, you should reapply the dark version each time it reverts in light mode

**Comment by Weilbyte** [comment]
It would be `apt upgrade` reverting it, yes. I will look into the possibility of an offline installer.

**Comment by erasedhammer99** [comment]
> Looking into it :)

Just checking in. How is the feature going? I realize it's probably low priority

**Comment by Weilbyte** [comment]
Been incredibly busy with real life stuff. It will most likely be done either tomorrow or Saturday.

**Comment by Weilbyte** [comment]
I have made progress with the offline installation feature in the new updated utility (#120). As of now, the installer enters offline mode when there is an "offline" folder in the cwd.

The offline folder must look like this:
offline/meta/[imagelist, supported]
offline/PVEDiscordDark/images/*
offline/PVEDiscordDark/js/PVEDiscordDark.js
offline/PVEDiscordDark/sass/PVEDiscordDark.css

There is still some way to go for complete offline installation, such as a GitHub action to automatically upload a zip file containing the installer and offline installation folder.

**Comment by erasedhammer99** [comment]
> I have made progress with the offline installation feature in the new updated utility (#120). As of now, the installer enters offline mode when there is an "offline" folder in the cwd.
> 
> The offline folder must look like this: offline/meta/[imagelist, supported] offline/PVEDiscordDark/images/* offline/PVEDiscordDark/js/PVEDiscordDark.js offline/PVEDiscordDark/sass/PVEDiscordDark.css
> 
> There is still some way to go for complete offline installation, such as a GitHub action to automatically upload a zip file containing the installer and offline installation folder.

Awesome! I really appreciate it.

**Comment by Weilbyte** [comment]
Should be completely done. GitHub actions workflow..
* attaches bundled zip artifact on every push to main
* attaches bundled zip artifact *and* uploads asset on every release
* attaches bundled zip artifact every month (maximum artifact storage in GitHub actions is 90d)
