### ISSUE TITLE
Tables have suboptimal coloring

### ISSUE THREAD

**Issue by Peronia** [Weilbyte/PVEDiscordDark#108]
See the examples, shot in the notes section with markdown:
![firefox_vJP0yCBWaP](https://user-images.githubusercontent.com/25049991/150343854-9a8edc40-168f-4952-8b5a-01f786c59dd4.png)

With hover the last row:
![firefox_sXUsrDfiou](https://user-images.githubusercontent.com/25049991/150343905-88b73668-f47f-45a1-9016-a26c85b46ba8.png)

**Comment by Weilbyte** [comment]
Currently having issues with my Proxmox install so will take me a bit to get to this.

**Comment by Weilbyte** [comment]
Coloring has been fixed
