### ISSUE TITLE
Feature Request: PBS Dark Mode

### ISSUE THREAD

**Issue by alexdelprete** [Weilbyte/PVEDiscordDark#110]
First of all, let me thank you @Weilbyte for the great work with this script: the dark mode is a must for PVE and should be included by default.

Question/request: I didn't dare to try it, but could the script work also for Proxmox Backup Server?

I just installed PBS to backup my PVE environment...but everything's white and I'm having great difficulties (white/light/bright colors stress my eyes a lot). It would be great if the script worked also on PBS installations.

Thanks,

Alessandro

**Comment by Cooba13** [comment]
There is fork of this repo called PBSDiscordDark by Luckyvb ;) Works pretty well on latest PBS

**Comment by alexdelprete** [comment]
> Works pretty well on latest PBS

Thank you so much. Will try it immediately. :)

**Comment by alexdelprete** [comment]
Tried it: seems to work fine on latest 2.1.1 but it warns that it support up to 2.0.7:

```
You might encounter issues because your version (2.1.1) is not matching currently supported versions (2.0.7 2.0.6 2.0.5 2.0.4 2.0.3 2.0.2 2.0.1 2.0.0 1.1.12 1.1.11 1.1.10 1.1.0).
If you do run into any issues on >newer< versions, please consider opening an issue at https://github.com/Luckyvb/PBSDiscordDark/issues.
```

**Comment by Cooba13** [comment]
yup but didnt see any issues so far, looks like just the install script neeeds to get updated by Lucky

**Comment by alexdelprete** [comment]
Yup, looks like it's working fine. Issues are not enabled on his repo, otherwise we could've given him a feedback. :)
