### ISSUE TITLE
Red border invisible on invalid fields

### ISSUE THREAD

**Issue by Peronia** [Weilbyte/PVEDiscordDark#111]
When proxmox have invalid fields, they are marked with a red border (in the proxmox design).
With this template, the mark is gone away.
Test it yourself: create a new CT with an id that is already given:
![grafik](https://user-images.githubusercontent.com/25049991/152116746-a9b571a1-fd16-423b-83ab-b8eec3a4da7c.png)

You see it only on hover.
Same for required fields like password, they don't show up until hover.

**Comment by Weilbyte** [comment]
Fixed by #116
