### ISSUE TITLE
Support for Proxmox Backup Server?

### ISSUE THREAD

**Issue by dorianim** [Weilbyte/PVEDiscordDark#117]
Hi,

I love your theme, and I'd like to use it not only for my pve, but also for [Proxmox Backup Server](https://www.proxmox.com/en/proxmox-backup-server).
Would it be possible to support it?

Regards,
Dorian

**Comment by DasLetzteEinhorn** [comment]
https://github.com/Luckyvb/PBSDiscordDark/

this works quite well :)

**Comment by dorianim** [comment]
Thanks! @Weilbyte are you willing to support it as well?

**Comment by Weilbyte** [comment]
@dorianim sorry for late reply. I am unable to at this time.
