### ISSUE TITLE
markdown table not respecting theme.

### ISSUE THREAD

**Issue by lue30499** [Weilbyte/PVEDiscordDark#118]
Hello,

In the notes sections, you can use markdown to create tables.
When creating a table it oscillates the row shade.
Please see below for an example between dark theme vs out of the box.
As you can see, every other row is bright.

<img width="772" alt="Screen Shot 2022-03-13 at 4 32 55 am" src="https://user-images.githubusercontent.com/63104612/158028551-8394ef01-6194-425a-b485-ed433ee175f2.png">

<img width="744" alt="Screen Shot 2022-03-13 at 4 32 39 am" src="https://user-images.githubusercontent.com/63104612/158028555-61235fba-8f4c-43e6-a7bc-d0bea70938cb.png">

Regards,
Lue

**Comment by lue30499** [comment]
haha i missed the existing ticket. Will close.

**Comment by Weilbyte** [comment]
fixed.
