### ISSUE TITLE
Missing Timer Icon

### ISSUE THREAD

**Issue by ShiroiKuma** [Weilbyte/PVEDiscordDark#12]
There should be a small timer icon here as this is a 14 hr backup, and with the standard theme, there is an icon here.

![image](https://user-images.githubusercontent.com/7948640/77545121-4b6d9a00-6eed-11ea-9f7d-ab911347b312.png)

**Comment by ShiroiKuma** [comment]
Standard Theme for Comparison

![image](https://user-images.githubusercontent.com/7948640/77545869-6987ca00-6eee-11ea-9ef1-0ecf436e603e.png)

**Comment by Weilbyte** [comment]
Slight error, will get it done tomorrow.

**Comment by Weilbyte** [comment]
Fixed :)
