### ISSUE TITLE
File not up?

### ISSUE THREAD

**Issue by Jpivz** [Weilbyte/PVEDiscordDark#126]
after i put in -  wget https://raw.githubusercontent.com/Weilbyte/PVEDiscordDark/master/PVEDiscordDark.sh

--2022-03-30 00:40:00--  https://raw.githubusercontent.com/Weilbyte/PVEDiscordDark/master/PVEDiscordDark.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘raw.githubusercontent.com’

then - bash PVEDiscordDark.sh install
bash: PVEDiscordDark.sh: No such file or directory

**Comment by ZEROPOINTBRUH** [comment]
just the one liner

**Comment by Weilbyte** [comment]
Response indicates DNS issues on your end.

**Comment by JamesonWelch** [comment]
I got this same response. Could someone guide me where to fix the DNS issue? Or at least where to start looking. I don't have my own DNS server running, and have no idea where to start looking to solve this.
