### ISSUE TITLE
No dark theme after update pve

### ISSUE THREAD

**Issue by weckie** [Weilbyte/PVEDiscordDark#127]
Hi,

Each time i update the pve the dark theme is gone.
Is there a fix for ?

kind regards,
Maarten Weckhuysen

**Comment by Cooba13** [comment]
Hello,
nope, when new pve update is performed it will overwrite theme files. That means you have to install theme again.

**Comment by Pascal3366** [comment]
Hi I have the same problem.

Is there a way to trigger the script after each update somehow ?

**Comment by Weilbyte** [comment]
Script doesn't have that functionality but you can write a cronjob or apt hook that checks the template file and runs the install script. The utility's `status` command will tell you if the theme is installed or not, and if not your script can simply just do an `install`.

**Comment by Pascal3366** [comment]
Ok I will try it
