### ISSUE TITLE
Alternate Rows no differentiated

### ISSUE THREAD

**Issue by ShiroiKuma** [Weilbyte/PVEDiscordDark#13]
Normally alternative grid rows (6.1.8) are between white/light grey, but with PVEDiscordDark that is gone.

![image](https://user-images.githubusercontent.com/7948640/77545285-8ec80880-6eed-11ea-9b2a-1f3b75784517.png)

**Comment by ShiroiKuma** [comment]
Standard Theme for Comparison

![image](https://user-images.githubusercontent.com/7948640/77545921-7b696d00-6eee-11ea-9cf9-c7af14dde905.png)

**Comment by Weilbyte** [comment]
Ah, thank you. I will spin up a Proxmox instance and take a look at it as soon as possible.

**Comment by Weilbyte** [comment]
Fixed!
