### ISSUE TITLE
PVE 7.2 - Ceph Pools  White Line

### ISSUE THREAD

**Issue by SkyDiver79** [Weilbyte/PVEDiscordDark#131]
Hello,
at PVE 7.2 i have under Ceph Pools after the last Pool a White Line.
This is the same on all updated Servers.
![Ceph-Pool](https://user-images.githubusercontent.com/104967400/166930760-a54d83b3-e985-4512-9a13-54946fc64d85.jpg)

**Comment by Weilbyte** [comment]
Will look into this
