### ISSUE TITLE
the cpu icon without theme on PVE7.2.3

### ISSUE THREAD

**Issue by kanned1079** [Weilbyte/PVEDiscordDark#132]
Datacenter > node1 > Summary, cpu icon is ok, But, each vm > Hardware, the processors icon without theme.
![20220507-122609](https://user-images.githubusercontent.com/58361983/167238267-3fcbc0f0-76eb-4bf3-8f37-6946a14d7878.png)

**Comment by Weilbyte** [comment]
Fixed with ca8c9f303768c68d4f5577ffd8b343684548c6b2
