### ISSUE TITLE
readme.md installation instructions

### ISSUE THREAD

**Issue by mattish91** [Weilbyte/PVEDiscordDark#137]
The first "two line command" could also be a one line command with:

`wget https://raw.githubusercontent.com/Weilbyte/PVEDiscordDark/master/PVEDiscordDark.sh && bash PVEDiscordDark.sh install`

Tested today as i updated lxc to 5.0.0-3 and works fine so far.

**Comment by Weilbyte** [comment]
I think it's good for visual clarity, changing it would also be redundant seeing as there is a one-liner version right underneath it.
Glad to hear it works for you.
