### ISSUE TITLE
Change Background-Color Pool Resource

### ISSUE THREAD

**Issue by Elwafi-Elmehdi** [Weilbyte/PVEDiscordDark#140]
proxmox 7.2.3
brave 1.41.96
chromium 103.0.5060.114

Hey maintainers you are doing great job, my eyes can't thank you enough,

The background color on icon of pools is close to the background color of the resource tab
I suggest to make it a bit lighter to give it more contexte

Keep it up

**Comment by djraw** [comment]
Check out https://github.com/Weilbyte/PVEDiscordDark/issues/142#issuecomment-1260157437, there I showed how to change the color of the pool icons (look for the "fa-tags" entries).
