### ISSUE TITLE
Doesn't seem to work on  7.2-7

### ISSUE THREAD

**Issue by hellrazorx64** [Weilbyte/PVEDiscordDark#141]
Finally dared to install this.
Went dead simple as, running the two commands.

Refreshed, rebooted the server, nothing happened. My eyes are still bleeding.

I'm running a cluster. Could this be an unsupported scenario? Should I install the theme on ALL my nodes for this to work?

Thank you

**Comment by Weilbyte** [comment]
Hi, have you tried clearing the browser cache? Clustered setups are supported, but the theme needs to be installed on the node serving the UI.

**Comment by hellrazorx64** [comment]
HI! Good to know! 
-Node serving the UI - Yes that is exactly my Goal, one node to Darken them all.
Somebody told me that the theme **needs** to be installed on **all** nodes within the cluster, but I'd rather not.

The problem was ALL my fault. I just realized I had two Dns pointing to the same (not the right) node.

Thank you
