### ISSUE TITLE
Oneliner not functoning

### ISSUE THREAD

**Issue by TheRealGramdalf** [Weilbyte/PVEDiscordDark#144]
The oneliner won't execute correctly (Yes, it was executed as root). It exits with: 

`bash: /dev/fd/63: No such file or directory`

Proxmox version `pve-manager/7.2-11/b76d3178 (running kernel: 5.15.60-1-pve)`

downloading the script manually and executing it as superuser still works

**Comment by Weilbyte** [comment]
Hi, I can only reproduce this when prepending `sudo` to the oneliner

**Comment by TheRealGramdalf** [comment]
That must be it. I was using the proxmox script to install on top of debian, since I was having trouble with the display when trying to use the proxmox installer (due to the server not having a great graphics card, as servers usually do). The default headless debian install doesn't set up a non-root user, so I was installing everything as root.
