### ISSUE TITLE
[Feature Request] Option For PBS [Proxmox Backup Server]

### ISSUE THREAD

**Issue by Gam3rrXD** [Weilbyte/PVEDiscordDark#147]
It would be really cool if we could be able to apply this theme to PBS so that when switching between PVE and PBS it is smoother and we would have a better experience. I am pretty sure that this could be done [Colors for sure] and I think (think) that all that needs to really be altered would be the icons. Hopefully, this can be implemented!

**Comment by Weilbyte** [comment]
Hi, for the time being this is not planned. Eventually I will attempt to rewrite the theme in a cleaner way, and after that I will look into PBS support. 

For the time being you could try this fork https://github.com/Luckyvb/PBSDiscordDark
