### ISSUE TITLE
Theme not work

### ISSUE THREAD

**Issue by p6002** [Weilbyte/PVEDiscordDark#158]
I installed and it doesn't work.

https://pastebin.com/YtJDeufA

Now I can't remove it!

https://pastebin.com/DJWTWV0b

**Comment by djraw** [comment]
So basically it was never installed.. no need to uninstall then anyway.
No issue in my book here.

**Comment by p6002** [comment]
Thanks, so there's no problem.

**Comment by djraw** [comment]
Oh wait!! I just realized, that you are in the wrong repo.. you used a fork by Luckyvb

And it seems he tries to adapt this script for the Proxmox backup server. So use this original repo instead and it should work as expected with PVE

**Comment by p6002** [comment]
`bash <(curl -s https://raw.githubusercontent.com/Weilbyte/PVEDiscordDark/master/PVEDiscordDark.sh ) install
`

Thanks again, it works now:
https://pastebin.com/KaigBis0

**Comment by djraw** [comment]
You‘re welcome! :)

And now you should delete the Pull request you opened ;)
