### ISSUE TITLE
Missing VirtIO RNG

### ISSUE THREAD

**Issue by JuddTracy-DAS** [Weilbyte/PVEDiscordDark#17]
Proxmox recently added VirtIO RNG support seen in the Add menu on the Hardware page.  This option does not show up with the theme installed.
![Add Hardware](https://user-images.githubusercontent.com/38507478/80524268-563ca400-895d-11ea-8942-ecfdfda54cbb.png)

**Comment by jonasled** [comment]
Audio Device is also missing

**Comment by jonasled** [comment]
I tried in on a new clean VM and the buttons are there after install. It happens only after install of the JS Mod

**Comment by jonasled** [comment]
I've written a fix, It should be available on approval by Weilbyte.
#18

**Comment by Weilbyte** [comment]
Thank you, merged. Will update the readme for the jsmod as well. Closing, reopen if issue persists.

**Comment by Weilbyte** [comment]
Additionally, jsmod will be revamped soon so issues like this do not happen again.
