### ISSUE TITLE
Graphs are light themed

### ISSUE THREAD

**Issue by jonchampagne** [Weilbyte/PVEDiscordDark#2]
All the graphs on summary pages are still light themed.

Light themed graph on a dark themed page:
![image](https://user-images.githubusercontent.com/1485633/53658065-d4040300-3c25-11e9-87f8-3f7704a67e6e.png)

**Comment by Weilbyte** [comment]
Aware of it. Though its not something I can change with CSS as the graphs colors are set by js.

**Comment by jonchampagne** [comment]
Makes sense. Just figured I'd mention it here, get the conversation started.

**Comment by Fusl** [comment]
How about adding this CSS?
```
.x-surface-canvas {
    filter: invert(100%);
}

.x-legend-item-marker {
    filter: invert(100%);
}
```
Doesn't look great but it's better than being blinded by a white graph:
![image](https://user-images.githubusercontent.com/2349496/58330163-98e52a80-7e36-11e9-87f1-9ef29367a6f7.png)

**Comment by Weilbyte** [comment]
That does look a little bit ugly but will work for now.
As for a better fix, I am currently working on editing the js files for the charts and its going well - though this is for the serverside option only.

**Comment by Weilbyte** [comment]
![image](https://user-images.githubusercontent.com/43392677/58339137-377a8700-7e49-11e9-9ec1-fdb470221f68.png)

This is how it looks so far, what do you think @Fusl

**Comment by jonchampagne** [comment]
I'll chime in that personally I don't mind the ugliness. It's still much easier on the eyes compared to a white background.

**Comment by Weilbyte** [comment]
Hm alright. I'll add it to the client-sided css soon.

**Comment by Fusl** [comment]
> This is how it looks so far, what do you think @Fusl
That one looks amazing. Have my vote for this for the server side option.

**Comment by ZeroPoke** [comment]
I personally actually like both of them.  Im vote for anything to give our eye some ease with the graphs.

**Comment by Weilbyte** [comment]
Going to add it into the repo today. Although it will only work for  PVE 5.4-3 as I do not have any servers running lower and the js files might differ by a lot.

**Comment by Weilbyte** [comment]
@Fusl I have put your suggestion in the browser extension style. The server-sided javascript modifications can be found [here](https://github.com/Weilbyte/PVEDiscordDark/tree/master/serverside/jsmod).

**Comment by ZeroPoke** [comment]
@Weilbyte Hey I dont believe you push those new invert CSS to the ddInstaller CSS file.  Not sure if that was intentional or not.

**Comment by Weilbyte** [comment]
@ZeroPoke intentional, the server-side version has a JavaScript bit that you can install to make the graphs dark. The inverted quick-fix is available for client-side only.

**Comment by Ethereal739** [comment]
@Weilbyte I am using Proxmox 6 right now and it works perfectly fine as well. I think you should add an option whether to install the JSMod or not in the install script or at least make a mention of it in the README, it will help a lot of people. :D

If you change the screenshot in the README to the dark graphs it would make everything look neater as well :)

**Comment by Weilbyte** [comment]
@Ethereal739 It is mentioned in the readme at the serverside instructions part. 

If you're on 6.0 it's not recommended to run the 5.4 JSMod as it replaces files some files. Though JSMod for 6.0 (6.0-4) is going to be out tomorrow and that should replace those somewhat incompatible 5.4 ones back to the usual 6.0 ones so no worries there.
