### ISSUE TITLE
line-highlighting in task log color issue

### ISSUE THREAD

**Issue by Drauku** [Weilbyte/PVEDiscordDark#20]
I found an issue with the theme. I checked the CSS code but couldn't figure out where to actually update the error-line background.
![image](https://user-images.githubusercontent.com/17952866/85959967-670d9400-b965-11ea-94af-8bb9cd88a892.png)
![image](https://user-images.githubusercontent.com/17952866/85960162-231b8e80-b967-11ea-9cb9-11b1245c3929.png)

Using the DarkReader Chrome extension makes it look like this, which is desirable. 
![image](https://user-images.githubusercontent.com/17952866/85960199-7e4d8100-b967-11ea-91c7-c0f4f568e267.png)
I was hoping it could be added to the actual CSS theme though.

Thanks for the effort put into this! Night-owl sys-admin eyes like mine thank you.

**Comment by jonasled** [comment]
I've fixed this error, so it should be available soon, if @Weilbyte approves it.

**Comment by Weilbyte** [comment]
That fixed it, thank you very much! 

There might be a rewrite to this since I myself, am not really liking how messy this all is.

**Comment by Drauku** [comment]
Thanks for the quick fix!
