### ISSUE TITLE
Request old version

### ISSUE THREAD

**Issue by Cnockaert-Mario** [Weilbyte/PVEDiscordDark#24]
Hello I am currently under the old version of proxmox and I would have needed your old version of ddinstall.sh but no way to make it work this one seeing that the repot does not exist any more possible to have a solution please

**Comment by Weilbyte** [comment]
Thanks for opening the issue. 

The old version is not supported anymore and the installer is not available (though I can make it available if you really want it) - only the uninstaller is as it's recommend to use the new version.

**Comment by Weilbyte** [comment]
What's your Proxmox version.

**Comment by Cnockaert-Mario** [comment]
My proxmox version is 5.4-15

**Comment by Weilbyte** [comment]
Have you thought about updating? 

Also try the new version, it might work for you.

**Comment by Cnockaert-Mario** [comment]
I have servers with version 6 on which the new Dark is installed, but I prefer not to upgrade to 6 on my old servers.

**Comment by Weilbyte** [comment]
The new version should also work on 5. Try it and if it doesn't seem to work then you can just uninstall the theme.

**Comment by Cnockaert-Mario** [comment]
python3 PVEDiscordDark.py

return:
```yml
  File "PVEDiscordDark.py", line 41
    print(f'{color}{text}{colors.NORMAL}', end=endc)
                                        ^
SyntaxError: invalid syntax
```

**Comment by Weilbyte** [comment]
That's weird. Update the Python3 package and try again. 

If that doesn't work I'll have the old install version up tomorrow.

**Comment by Cnockaert-Mario** [comment]
I forced the recent version python shift and it doesn't change anything I have the impression that we're going to need the old version.

**Comment by Weilbyte** [comment]
Try using [this](https://github.com/Weilbyte/PVEDiscordDark/blob/old/serverside/ddInstall.sh) to install the old theme.

**Comment by Cnockaert-Mario** [comment]
Thank you for the link this worked well I advise to keep it available for customers ;)

**Comment by Weilbyte** [comment]
No problem, glad it worked!
