### ISSUE TITLE
Can you make an unattended version?

### ISSUE THREAD

**Issue by garbled1** [Weilbyte/PVEDiscordDark#25]
I would like one I could run via ansible or a script after applying an upgrade to proxmox.  Maybe just like a -I install option?

BTW - love the new theme, looks amazing.

**Comment by Weilbyte** [comment]
Ah great idea, will be done within a day or two.

**Comment by Weilbyte** [comment]
Should be added with https://github.com/Weilbyte/PVEDiscordDark/commit/692442eb964d473c2d37de30d387a51699a827ed. 
Please try it out and tell me what you think :) 

Simply pass `--action {install, uninstall}` as an argument. `-a` works too!

**Comment by zimmertr** [comment]
```bash
root@earth:~# python3 /tmp/PVEDiscordDark.py --action install

PVE 6.2-4 detected.

[~] PVEDiscordDark Utility

Backing up index template file..
Downloading stylesheet..
Downloading patcher..
Applying stylesheet and patcher..
Downloading images [21/21]..

Theme installed successfully!
```

This worked for me! Thank you!
