### ISSUE TITLE
Syntax issue on line 45

### ISSUE THREAD

**Issue by techano** [Weilbyte/PVEDiscordDark#26]
Command issued: python3 PVEDiscordDark.py
Error received:
![image](https://user-images.githubusercontent.com/20607160/91651638-e726a780-ea43-11ea-934b-8eaff2f22ff7.png)
Proxmox version: 5.3-8

**Comment by jonasled** [comment]
Are there more details below, because I can't reproduce the error

**Comment by jonasled** [comment]
And can you please poste your Python Version (`python3 --version`)

**Comment by zimmertr** [comment]
Install successfully worked for me using the script [here](https://raw.githubusercontent.com/Weilbyte/PVEDiscordDark/master/PVEDiscordDark.py) and `python3 /tmp/PVEDiscordDark.py --action install`

```bash
root@earth:~# pveversion
pve-manager/6.2-4/9824574a (running kernel: 5.4.34-1-pve)

root@earth:~# python3 --version
Python 3.7.3
```

**Comment by Weilbyte** [comment]
Are you using the latest script? If so then please provide Python3 version.

**Comment by techano** [comment]
I made this issue in regards to another person who was having the issue and they will be responding to your questions regarding their issue.

**Comment by CCTrollz** [comment]
Apologies for the wait.
```cart@cerberus:~$ python3 --version
Python 3.8.2```

**Comment by jonasled** [comment]
It looks like your python version is to old, can you please upgrade to a version newer than 3.6

**Comment by jonasled** [comment]
I've made some changes to the installer script which also should fix the problem.

**Comment by Weilbyte** [comment]
Merged.

**Comment by Weilbyte** [comment]
Reopening as https://github.com/Weilbyte/PVEDiscordDark/blob/master/PVEDiscordDark.py#L91 uses fstrings (will solve a bit later).
