### ISSUE TITLE
Smart Values have white background

### ISSUE THREAD

**Issue by jonasled** [Weilbyte/PVEDiscordDark#29]
I've tried to read the S.M.A.R.T values from my NVME / SAS Disks, but you can't read them because of the white background. Sata disks are working fine.

![image](https://user-images.githubusercontent.com/46790650/91701683-f149c280-eb77-11ea-87ab-9c9af81f7e2b.png)

**Comment by jonasled** [comment]
It looks like, there is a problem with [dd_patcher.js Line 44](https://github.com/Weilbyte/PVEDiscordDark/blob/master/PVEDiscordDark/js/PVEDiscordDark.js#L44). According to chrome `PVE.DiskSmartWindow is not defined. Proxmox Version is here: https://hastebin.com/onucehufoz.http

**Comment by jonasled** [comment]
And the same also occurs on the package version Window

**Comment by Weilbyte** [comment]
They have changed the names of some windows with that release. On it!

**Comment by Weilbyte** [comment]
Unable to replicate white background on package version window.

**Comment by Weilbyte** [comment]
Closing because of no response. 
@jonasled  Re-open if it happens again as I cannot seem to find the white for the package version window.

**Comment by jonasled** [comment]
I've updated the mod and everything works fine, thanks.
