### ISSUE TITLE
Light background makes text unreadable

### ISSUE THREAD

**Issue by Ethereal739** [Weilbyte/PVEDiscordDark#3]
First of all, I want to thank you for this theme. It is absolutely amazing and it doesn't hurt my eyes like the default light theme. 

However, I noticed that in some places, there are light text on light background and it is practically unreadable. I hope you could fix this:

![image](https://user-images.githubusercontent.com/42406302/67265833-b6b5ca80-f47c-11e9-9963-a20ba8820cc2.png)

**Comment by Weilbyte** [comment]
Thanks!  

I will update the theme soon for it to work better with newest version. I'm aware of this issue that you mention. 

Would help out a bunch if you write down the other places where you encounter this issue.

**Comment by Weilbyte** [comment]
Should be fixed by 217ce37 
Let me know if you encounter any issues.

**Comment by Ethereal739** [comment]
Wow, thank you so much for the quick fix. I am having the same issue when going to a node and clicking on view packages, I hope you could fix that as well :D

**Comment by Weilbyte** [comment]
By view packages I assume you mean the 'Package versions' at the Summary page of the node? Or are you talking about something else?

**Comment by Ethereal739** [comment]
Yeah, my bad. I meant the "Package versions" at the Summary page :)

**Comment by Weilbyte** [comment]
I believe the JS modification takes care of that if the style itself doesn't. Speaking of which I am currently working on the JS modification for 6.0 (6.0-4), which should be out tomorrow. 

Going to also brighten up the new user button (the one at the top-right) and fix a bug that 217ce37 introduced with the 'My Settings' part of said button. 

After all of that is done I'm going to push all of tonight's changes to the browser-extension version.

**Comment by Weilbyte** [comment]
@Ethereal739 JSMod for 6.0-4 is out, plus some bugfixes and changes for the theme. For the server-side theme run `ddRemove.sh` and then run `ddInstall.sh` right after.

**Comment by whalehub** [comment]
@Weilbyte I installed this theme earlier today and it looks like the issue affecting the package versions appeared again.

**Text unselected**
![vivaldi_2020-07-07_14-04-50](https://user-images.githubusercontent.com/44198148/86785742-f9472380-c05a-11ea-9fe7-ab25d1ccc93f.png)

**Text selected**
![vivaldi_2020-07-07_14-05-04](https://user-images.githubusercontent.com/44198148/86785774-07953f80-c05b-11ea-9ed6-2d79a2133306.png)
