### ISSUE TITLE
Internet Connection required while connected to the Internet

### ISSUE THREAD

**Issue by Kuntish** [Weilbyte/PVEDiscordDark#30]
I ran the script with python3.7 and it tells me to connect to the internet while the node is already connected

![grafik](https://user-images.githubusercontent.com/51027149/93266661-ae5c3180-f7aa-11ea-93ff-2b16cd5f6d20.png)

**Comment by Weilbyte** [comment]
The internet check is a ping ran against `github.com`, make sure your DNS is working, that `github.com` is resolvable and double-check if you have any issues with IPv6.

**Comment by Kuntish** [comment]
github.com is reachable from the node I am trying to run the script from. What do you mean "any issues with IPv6"?

**Comment by Weilbyte** [comment]
Just in case your system is preferring v6 over v4. 

What's your ping to GitHub?

**Comment by Kuntish** [comment]
My ping to github from the node is fine
![image](https://user-images.githubusercontent.com/51027149/93309051-5998d500-f803-11ea-85ce-1ca900f57ea8.png)

**Comment by Weilbyte** [comment]
Odd. Remove line 172 from the install script if it's checkConn().

**Comment by Kuntish** [comment]
It seems like my Python3.7 installation has an error, I just ran some tests and they failed for the most part. I'll close the ticket and hope that a reinstall will fix it
