### ISSUE TITLE
Changelog has white background for pending Updates.

### ISSUE THREAD

**Issue by abjoseph** [Weilbyte/PVEDiscordDark#33]
Firstly, I wanted to say thanks for the work you've done here. It's being a true pleasure to use Proxmox without the blinding white backgrounds.

Below is a screenshot and some relevant information, let me know if you need any additional details:

- Proxmox Version: 6.2-11
- Last download of PVEDiscordDark: 09-20-2020
- Python Version: Python 3.7.3
- Screenshot of white background whenever you double-click on a pending update...

![image](https://user-images.githubusercontent.com/26844547/94155196-aeb09880-fe4c-11ea-980f-a16e7d9745e4.png)

**Comment by Weilbyte** [comment]
Should be fixed now, uninstall and reinstall theme with the installer. Clear browser cache if still doesn't work.

**Comment by abjoseph** [comment]
That fixed it, much appreciated.
