### ISSUE TITLE
Datacenter>HA>Add button not working when theme enabled

### ISSUE THREAD

**Issue by nashosted** [Weilbyte/PVEDiscordDark#34]
Datacenter>HA>Add button not working when theme enabled. When disabled it works fine.

**Comment by Weilbyte** [comment]
Able to replicate, thank you! Working on a fix asap.

**Comment by Weilbyte** [comment]
Issue fixed. Doing a reinstall through the utility will be enough to get it.

**Comment by nashosted** [comment]
> 
> 
> Able to replicate, thank you! Working on a fix asap.

Thanks!
