### ISSUE TITLE
Migrate paper airplane color?

### ISSUE THREAD

**Issue by brettferrell** [Weilbyte/PVEDiscordDark#35]
Any chance we can change the migrate "paper airplane" color, it's awfully dark and hard to see?

**Comment by Weilbyte** [comment]
Huh, I assume you mean the template context menus having blurple as the background like here: 
![image](https://user-images.githubusercontent.com/43392677/94370380-0589cc80-00f0-11eb-88f4-4c8c739c3e1c.png)

**Comment by brettferrell** [comment]
Sorry, no, I meant when it's actually in motion... this little guy right here...

![migrating](https://user-images.githubusercontent.com/17435789/94378805-2c4d0080-00fa-11eb-82ea-01e6440196e4.png)

**Comment by KoKos024** [comment]
I agree, the first time I thought my migration crashed/stopped before i looked closely at the icon.

**Comment by Weilbyte** [comment]
Ah, got it! Will be fixed today.

**Comment by Weilbyte** [comment]
![image](https://user-images.githubusercontent.com/43392677/94678068-351e1c00-031e-11eb-9658-857807fe8e90.png)
How does this look?

**Comment by brettferrell** [comment]
Works for me.  I'd prefer the green color as a little more noticeable, but it's a LOT better than the black...

**Comment by Weilbyte** [comment]
How would yellow do?

**Comment by Weilbyte** [comment]
Fix should be out, just reinstall theme via the installer utility!
