### ISSUE TITLE
Borders around toolbars

### ISSUE THREAD

**Issue by Codebreaker101** [Weilbyte/PVEDiscordDark#37]
Is it possible to add borders around toolbars like in the picture bellow? Tables, charts, and buttons seem to float about (to me at least). 

![68747470733a2f2f692e696d6775722e636f6d2f536e6c437948462e706e67](https://user-images.githubusercontent.com/16204269/94776790-a7e0d300-03c2-11eb-8330-599dd78acbe3.png)

**Comment by Weilbyte** [comment]
They are sort of supposed to float like that. But I will see about adding borders like that in the following days.

**Comment by Weilbyte** [comment]
Added in, thanks for the suggestion! And sorry for being late.

The borders are currently around DC, Node, QEMU, LXC and Storage windows.
