### ISSUE TITLE
dd_logo.png - wrong proportions

### ISSUE THREAD

**Issue by Xenthys** [Weilbyte/PVEDiscordDark#39]
Hello,

It appears the `dd_logo.png` asset is stretched, unlike the original and its blurple counterpart.  
I have recolored the original to ensure the real proportions were kept, you can use it of course:

![dd_logo](https://user-images.githubusercontent.com/15252571/95007164-c0dcc480-060c-11eb-9f47-b55d0fd60f1f.png)

Feel free to replace as-is, I don't want any credit since it took a second to notice the issue and another to recolor.

Have a nice day!

**Comment by Weilbyte** [comment]
Thanks!
