### ISSUE TITLE
Main panel selected category highlight

### ISSUE THREAD

**Issue by ryantrip** [Weilbyte/PVEDiscordDark#4]
The selection highlight of the categories on the main panel do not span across the entire row.

Replicated in both Chrome and Safari on MacOS.

Screenshot attached:
![Screen Shot 2019-11-08 at 5 57 26 PM](https://user-images.githubusercontent.com/24561062/68520988-559a3f00-0251-11ea-9357-0f04a721a8f2.png)

**Comment by Weilbyte** [comment]
Intended behavior.
