### ISSUE TITLE
White stripe pve in updates

### ISSUE THREAD

**Issue by angelkiller2** [Weilbyte/PVEDiscordDark#40]
There is a white stripe in pve updates site.

![white stripe](https://user-images.githubusercontent.com/15493231/95049232-a3c9f380-06e9-11eb-9c62-3027bbba09c2.PNG)

**Comment by Weilbyte** [comment]
Will get to fixing it tomorrow, thanks!

**Comment by Weilbyte** [comment]
Fixed. Sorry for taking so long!
