### ISSUE TITLE
Tick boxes disappeared 

### ISSUE THREAD

**Issue by MonsieurPoutounours** [Weilbyte/PVEDiscordDark#41]
Hi,

In Proxmox VE 6.2-15, installing the theme make all the tick boxes disappear (like firewall in a network interface or purge in the destroy screen).

Uninstalling with the script does not fix the problem.

**Comment by Weilbyte** [comment]
I will take a look at this soon. Thanks for bringing it up.

**Comment by DarkIllusi0n** [comment]
Are you talking about these? I'm on VE 6.2-15 (no subscription) and I don't seem to have the issue.
I did have the "[aria](https://lunar.computer/posts/themes-proxmox/)" theme applied before installing this theme if that matters. 
![tick](https://user-images.githubusercontent.com/5461458/99454393-f6ebb480-28eb-11eb-854a-46d4dd172279.png)

**Comment by MonsieurPoutounours** [comment]
Yes, these boxes.
No theme installed before and running the script make them disappear. 
Happened on two of my hypervisors.

**Comment by Weilbyte** [comment]
@MonsieurPoutounours I have installed a brand new Proxmox VM with 6.2-15 and installed the theme onto it and so far, all the checkboxes look normal. 
![image](https://user-images.githubusercontent.com/43392677/99538111-c881de00-29ac-11eb-962f-579cf3f78962.png)

Can you try refreshing the page with cache disabled?

**Comment by MonsieurPoutounours** [comment]
Same thing happened on a brand new browser, so it may not be cache related.
Reloading cache did not helped.

Although, it is back today, without doing anything.
Some things have changed on my PC / network, so i think the script is not to blame.

Sorry for the noisy issue and thank you for your time.

**Comment by Weilbyte** [comment]
No problem! Glad it was resolved.
