### ISSUE TITLE
Add hover affect to tree list

### ISSUE THREAD

**Issue by frenzymind** [Weilbyte/PVEDiscordDark#42]
Hello. If you check common proxmox theme - there is hover affect on containers and storages in tree view:
![prox-common-hover](https://user-images.githubusercontent.com/33678873/99760852-ac5a7a00-2b2f-11eb-9d71-ea5ed3a25504.jpg)
In this dark theme no that effect.
![prox-dark-hover](https://user-images.githubusercontent.com/33678873/99760858-b2e8f180-2b2f-11eb-9766-f762691289c1.jpg)

It would be nice to see hover affect on that items , because it is a little bit confused without it when you move cursor throught list.
Thanks!

**Comment by Weilbyte** [comment]
Would this be good enough?
![image](https://user-images.githubusercontent.com/43392677/100134854-202ab880-2e89-11eb-9f5d-ae53afecf59e.png)

**Comment by frenzymind** [comment]
That is cool! Thank you very much!
