### ISSUE TITLE
Calendar are not dark moded

### ISSUE THREAD

**Issue by RisedSky** [Weilbyte/PVEDiscordDark#43]
Hello, it seems that the calendar is not dark moded (in API token i found this)
And we can't see the 2020 on it too
I have the latest version of the dark mode

![image](https://user-images.githubusercontent.com/23197999/99904537-b0bb9a00-2ccb-11eb-8f60-d6a209e4fc04.png)

**Comment by Weilbyte** [comment]
Will look somewhat like this. 
![image](https://user-images.githubusercontent.com/43392677/100121016-ece02d80-2e78-11eb-841d-d637d779e6c6.png)
