### ISSUE TITLE
Proxmox Backup Server support?

### ISSUE THREAD

**Issue by djarbz** [Weilbyte/PVEDiscordDark#44]
Now that PBS is considered stable with v1, is this theme support or will you consider creating a theme for PBS?

**Comment by Weilbyte** [comment]
I do not use PBS but I will take a look at it to see if something can be done.

**Comment by djarbz** [comment]
Thanks, from what I can tell, the frontend UI is shared with PVE.
But I am not 100% sure what you all did in your JS and CSS.

**Comment by Weilbyte** [comment]
There is a lot to do to make the UI for PBS fully dark like this one. They do have some shared elements but its not all of them. I don't use it enough at the moment to know how it fully works and it is too much work for me.
