### ISSUE TITLE
Invisible checkboxs

### ISSUE THREAD

**Issue by frenzymind** [Weilbyte/PVEDiscordDark#48]
Hello!
I found at least 2 checkbox are visually hidden with dark theme: when you create VM on memory tab "Balloon" option and confirm tab "start after created"
![hidden1](https://user-images.githubusercontent.com/33678873/102034202-69bb5300-3df8-11eb-8fcf-312e1df46174.jpg)
![hidden2](https://user-images.githubusercontent.com/33678873/102034211-6c1dad00-3df8-11eb-9f6f-b9878e00d767.jpg)

**Comment by Weilbyte** [comment]
They are present for me. Please take a look at #41.

**Comment by frenzymind** [comment]
Hmm, after couples refreshes of page they back :)
Strange behavior.

**Comment by Weilbyte** [comment]
Glad its fixed.
