### ISSUE TITLE
Selected days of week are not visible

### ISSUE THREAD

**Issue by abrondijk** [Weilbyte/PVEDiscordDark#52]
I just installed the darktheme and it's great! However, I noticed that with the theme enabled, there is no way to see which days of the week are enabled on the backup dialog, as seen [here](https://imgur.com/a/QkGLWyh).

The same goes for which containers/VMs are selected in that same dialog.

**Comment by Weilbyte** [comment]
I see the issue, would be helpful if you could also include the path you took in the UI to get to that dropdown. Additionally, have you encountered this issue in more places?

I will get to working on this in 1-2 days.

**Comment by abrondijk** [comment]
Right yeah that would have been a good idea..

Datacenter (at the left panel) -> backup -> doubleclick any scheduled backup
In the dialoge that pops up there, the different containers/VMs like I said, as well as the "Day of Week" dropdown.

I've looked around for similar issues but I couldn't find any. I'll update this issue if I do.

Thanks!

**Comment by Weilbyte** [comment]
Thank you, will be fixed tomorrow!

**Comment by Weilbyte** [comment]
Has been fixed, if you encounter this issue again please re-open!

**Comment by abrondijk** [comment]
Awesome, thank you! Looks good
