### ISSUE TITLE
Rework icon coloring

### ISSUE THREAD

**Issue by Weilbyte** [Weilbyte/PVEDiscordDark#59]
Currently, icon recoloring is handled in a bad way. Many icons are styled white on their own, while a simple `color: white` to their shared parent class would do the exact same.

In short: remove useless styles, recolor parent and have children inherit color, clean mess.

**Comment by ianalexis** [comment]
Don’t know if it is the correct place to upload this but I’m trying to make a black fork so I remaster and remake some icon files.
If this helps you please use it and if you need something else please make me know.

![bl_tool-spritesBACKGROUND](https://user-images.githubusercontent.com/12130714/109869537-c421be00-7c47-11eb-9da3-dea25455e61c.png)
![bl_tool-spritesBACKGROUDLESS](https://user-images.githubusercontent.com/12130714/109869925-3db9ac00-7c48-11eb-8ddd-50ef7beead7b.png)
