### ISSUE TITLE
Blue color on console makes it impossible to read

### ISSUE THREAD

**Issue by IT-Anthony** [Weilbyte/PVEDiscordDark#6]
Can you change that color ? I maked the installation and it seems to be okay, but the blue lines are nearly impossible to read...

![image](https://user-images.githubusercontent.com/54004140/76712147-18215300-6716-11ea-9e9b-e224eb268167.png)

**Comment by jonasled** [comment]
I've made a pull request to change this.

**Comment by Weilbyte** [comment]
Sorry @IT-Anthony for very late response, I did not receive a notification for this issue. Closing as the PRs by @jonasled solve the issue.
