### ISSUE TITLE
Bad icon colors.

### ISSUE THREAD

**Issue by xickwy** [Weilbyte/PVEDiscordDark#60]
Hi!

I've see two icons with wrong path. I don't sure where, if in the jss patch or in the css. I don't know why but the icon is installed but the frontend show the black icon. Those are the PBS icon and the ISO icon.

![PBSIcon1](https://user-images.githubusercontent.com/69851760/105609401-557c5580-5da9-11eb-8abf-a12cbdabe9b0.png)
![ISO1](https://user-images.githubusercontent.com/69851760/105609411-662ccb80-5da9-11eb-8c83-5933b6e53f29.PNG)
![ICON2](https://user-images.githubusercontent.com/69851760/105609381-3b427780-5da9-11eb-8756-ba1045c5934c.PNG)

**Comment by Weilbyte** [comment]
The icon colorings are going to be redone as per #59. Thanks!

**Comment by jonasled** [comment]
Proxmox today relesed PVE 6.4 and there are a lot more missing icons

**Comment by Weilbyte** [comment]
I will take a look. Update might take a while.

**Comment by Weilbyte** [comment]
@jonasled Should be fixed, open an issue if there are any more missing ones :)
