### ISSUE TITLE
Multi-select Dropdown can have better color differentiation

### ISSUE THREAD

**Issue by prashanthgmuralidhar** [Weilbyte/PVEDiscordDark#61]
![image](https://user-images.githubusercontent.com/11925173/107476930-d9ea1900-6b9c-11eb-86bf-a8c83e1b3402.png)
Hi I'm not sure if this is the correct way to post issues but was wondering if the coloring for multiselect drop-downs( example the content drop-down in storage menu) can be made to be more distinct. I find it a bit difficult to see the difference between what is selected and not selected.
Thanks and the theming is great BTW.

**Comment by Weilbyte** [comment]
Thanks, will take a look on Monday.
