### ISSUE TITLE
Missing top inner border when category selected in folder view

### ISSUE THREAD

**Issue by Codebreaker101** [Weilbyte/PVEDiscordDark#65]
When Folder View is selected and you select Nodes for example, there are missing inner border as shown bellow. 

![Screenshot from 2021-03-06 07-30-02](https://user-images.githubusercontent.com/16204269/110197744-eedd6380-7e4d-11eb-8811-33a19339a45d.png)

**Comment by Weilbyte** [comment]
Thanks, will take a look soon.

**Comment by Weilbyte** [comment]
Sorry for taking long, it is now fixed.
