### ISSUE TITLE
Scrollbar is missing

### ISSUE THREAD

**Issue by lue30499** [Weilbyte/PVEDiscordDark#66]
Hello,

The horizontal scroll bar in the datacenter view for the nodes is missing, but is still able to be interacted with.

There might be other missing scrollbars, but this is the most obvious one as it is horizontal and doesn't work with the scroll wheel.

A video of the issue:
https://drive.google.com/file/d/1IhclhQJUomPehbqjumj2ZO1CocLQLTrN/view?usp=sharing

Regards.

**Comment by Weilbyte** [comment]
I see, will be fixed within a 4 days.

**Comment by Weilbyte** [comment]
Should be more visible now!
