### ISSUE TITLE
After upgrade of PVE the theme can't be installed again with the .sh

### ISSUE THREAD

**Issue by Niemand112233** [Weilbyte/PVEDiscordDark#72]
Hi,

with the python script everything works fine, but with the new .sh file I have the problem that after upgrading proxmox (which removes the theme) I can't install your theme anymore. 
```

root: bash PVEDiscordDark.sh install
Theme already installed
```

But the page is still white.

Edit: If I uninstall it first then it works. It would be nice if you could insert it into the .sh file.

**Comment by wildcodefox** [comment]
Instead of bash PVEDiscordDark.sh install, use bash PVEDiscordDark.sh update

**Comment by Weilbyte** [comment]
As wildcodefox pointed out, you need to run `bash PVEDiscordDark.sh update` which will uninstall and then install the theme. 

The issue itself comes from Proxmox updates overwriting the HTML template file (where the PVEDD stylesheet and patcher are included/linked). 

I will however add instructions after `Theme already installed` message to tell the user to run the update command if they have updated Proxmox.
