### ISSUE TITLE
[Suggestion] Upstreaming changes

### ISSUE THREAD

**Issue by whalehub** [Weilbyte/PVEDiscordDark#78]
I think it might be worth investigating whether or not the devs at Proxmox are open to implementing native dark theme support on the basis of this repository.

**Comment by zaee-k** [comment]
Totally agree, this dark theme is awesome

**Comment by Weilbyte** [comment]
I have thought about this but while the CSS works, it is messy and would not be accepted upstream.

**Comment by jonasled** [comment]
As a sidefact, there is already a note on their bugzilla to add support: https://bugzilla.proxmox.com/show_bug.cgi?id=2961
