### ISSUE TITLE
add proxmox 7.0 to supported versions

### ISSUE THREAD

**Issue by eins** [Weilbyte/PVEDiscordDark#79]
Howdy  Weilbyte 
proxmox 7.0 is out.

I upgrade my proxmox cluster from 6.4 to 7.0, and installed PVEDiscordDark after it.
the colors are the same but there is a warning when you first installed it

```sh
bash PVEDiscordDark.sh install
You might encounter issues because your version (7.0) is not matching currently supported versions (6.4 6.3 6.2 6.1).
If you do run into any issues on >newer< versions, please consider opening an issue at https://github.com/Weilbyte/PVEDiscordDark/issues.
✔ Backing up template file
✔ Downloading stylesheet
✔ Downloading patcher
✔ Applying changes to template file
```

thanks again for this great dark theme.

**Comment by Weilbyte** [comment]
Depends on #80. Going to do some further testing to see if anything else is changed too much.

**Comment by Weilbyte** [comment]
Added to list. Run `bash PVEDiscordDark.sh update` to get the changes.

**Comment by eins** [comment]
> Added to list. Run `bash PVEDiscordDark.sh update` to get the changes.

I tested in an other cluster. It works

```
bash PVEDiscordDark/PVEDiscordDark.sh install
✔ Backing up template file
✔ Downloading stylesheet
✔ Downloading patcher
✔ Applying changes to template file
✔ Downloading images (24/24)
Theme installed.
```
