### ISSUE TITLE
PVE 7.0

### ISSUE THREAD

**Issue by Weilbyte** [Weilbyte/PVEDiscordDark#80]
Some issues I discovered..
* ~~No color for AD/LDAP/OpenID icons on the Add dropdown button under `DC => Permissions => Authentication`.~~
* ~~When clicking on a button, the button will become grey/white.~~
* ~~Certain windows have wrong text color (as example, see `DC => Storage => Add => PBS` window encryption tab)~~
* ~~Wrong text color for `/etc/apt/sources.list` text under `Node => Updates => Repositories`~~
* ~~Right click context menu on server view left-side-panel thing is absolutely borked.~~
* ~~White borders on graph buttons under CT/VM summary views (and other places using graphs)~~
* ~~No color for "view" button under `CT/VM => Task History` (icon is new addition)~~

Probably more. Need further testing.

**Comment by valdearg** [comment]
Tiny little thing:

![image](https://user-images.githubusercontent.com/2789033/125204042-24b6ac80-e273-11eb-8205-7849e910c5f5.png)

The "pve-no-subscription" part.

**Comment by Weilbyte** [comment]
@valdearg Not PVE 7.0 exclusive as it has to do with the background color of warnings for grid/table elements. But I have noticed it and will fix it soon 👍
