### ISSUE TITLE
Warning message unreadable

### ISSUE THREAD

**Issue by BenSchol** [Weilbyte/PVEDiscordDark#82]
Hi,

First of all, I really like your dark theme. However I found an issue with warning messages. Attached is a screenshot from Proxmox 7.0 VE item Repositories. As you can see the text is unreadable.

Kind regards, Ben

<img width="1491" alt="Screenshot 2021-07-14 at 16 47 49" src="https://user-images.githubusercontent.com/38049507/125642716-626766e2-8bb2-4a13-9f88-f7acab7a15bb.png">

**Comment by Weilbyte** [comment]
Sorry for the delay, will be solved in 3 days when I return from vacation.
