### ISSUE TITLE
Dark Theme removes Acme option under Datacenter (Proxmox 7.0-10)

### ISSUE THREAD

**Issue by RavHilton** [Weilbyte/PVEDiscordDark#83]
![Screen Shot 2021-07-16 at 14 44 19](https://user-images.githubusercontent.com/49377971/125893099-0433b2fb-f9aa-4763-82df-047cefe89dc6.png)
![Screen Shot 2021-07-16 at 13 36 42](https://user-images.githubusercontent.com/49377971/125893102-769d477b-89b4-438e-bfed-8d145de07523.png)

As you see from the attached screenshots, once the Dark Theme is installed and enabled, Proxmox 7.0-10 (and also 7.0-9) loses the Acme option for the Datacenter.

Even if you type in https://proxmox.example.com:8006/#v1:0:18:4:=certificates:=contentBackup::::=consolejs:=acme the page cannot be displayed.

**Comment by c1nema** [comment]
Hi,

Something seems to be gone wrong in your theme patching or something else.

I just installed a fresh copy of Proxmox (same version as you, 7.0-10) and i can perfectly see the "ACME" option + it's working as expected

![grafik](https://user-images.githubusercontent.com/16503129/125948589-bdade84f-6ff1-41bd-a8fb-43938dceeb97.png)

**Comment by Weilbyte** [comment]
This is odd, as both on my main Proxmox host and my testing Proxmox VM (running 7.0-9 and 7.0-10) still have the ACME option with the theme enabled. 

How did you update to Proxmox 7.0-10? And when running the theme, refresh page and check if there are any errors in the F12 console. 

Additionally, provide the output of the following command: `sha1sum /usr/share/pve-manager/js/pvemanagerlib.js /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js`

**Comment by RavHilton** [comment]
I installed Proxmox, updated, installed the theme and ACME was there.  I logged out of the Proxmox GUI and then back in and it was gone.  BUT - and I just remembered this - I have logged in as a non-root user as I'm not a fan of using root on the console (for obvious reasons) - but this different user is part of the Admin group, that has Admin girights assigned in Permissions.  Maybe this is part of it?

Also, attached is the F12 error report on a refresh...
![Screen Shot 2021-07-17 at 10 45 29](https://user-images.githubusercontent.com/49377971/126020356-429dd8eb-78b9-4be0-971d-a5f143d1171d.png)

sha1sum /usr/share/pve-manager/js/pvemanagerlib.js /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js gives:
91efa264d2763d7cf34a601e4b9d3fb6c9602bfd  /usr/share/pve-manager/js/pvemanagerlib.js
0b1c003114b622a2871dbbd531e9cd5731f194f4  /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js

**Comment by RavHilton** [comment]
...and nope, when I re-enabled the root login and logged in as root, the Acme option was still unavailable.

Also, I don't know if you saw in the original Dark image I posted, but there are no expand/contract arrows on Datacenter and the node.

**Comment by RavHilton** [comment]
I just ran the update process (as user=root) and both ACME and the arrows have returned.

Logged out and back in as the other user and Acme has disappeared again.  Interesting - looks like there may have been initially an install issue (as per the F12 report) but also there's an issue in Proxmox 7 wrt "Admin" users and access to ACME - I'll report that over there...

**Comment by Weilbyte** [comment]
Weird. So to double-check, the theme works fine now (no F12 errors) and the ACME issue seems to be related to Proxmox 7 itself?
