### ISSUE TITLE
Any chance of getting a version of this for Proxmox Backup Server?

### ISSUE THREAD

**Issue by fsociety3765** [Weilbyte/PVEDiscordDark#89]

**Comment by jonasled** [comment]
No, the mod is only for PVE, PBS or PMG needs a different mod which is not available.

**Comment by madindehead** [comment]
I was wanting to ask the same thing. I assume that any version for PBS would be completely separate project, but could re-use some of the existing assets and work. 

I really have no idea how to start this, but I would be keen to learn.

**Comment by Weilbyte** [comment]
Only PVE is supported with this repository.
