### ISSUE TITLE
Buttons are too bright and wash out white text

### ISSUE THREAD

**Issue by anladwig** [Weilbyte/PVEDiscordDark#95]
The action buttons on the upper right (and anywhere else they appear) are not properly dark themed and appear light blue with white text. The buttons should be a darker blue to get the appropriate amount of contrast between the foreground and the background of the buttons.
![image](https://user-images.githubusercontent.com/24319176/141408272-d3aefcb2-10ae-486a-bc32-d7a92a19c133.png)

**Comment by Weilbyte** [comment]
Should have better contrast with #96

**Comment by anladwig** [comment]
Thank you so much! I was looking into how to change it mywelf, but wasn't sure how to test it out just yet.

**Comment by Weilbyte** [comment]
Went from a contrast ratio of 3.33:1 to 4.7:1 (with white text), reopen if you feel like it should be more.
