### ISSUE TITLE
White Dialog in PVE 7.1

### ISSUE THREAD

**Issue by djraw** [Weilbyte/PVEDiscordDark#97]
Hi there, first of all thank you for the great theme! I upgraded to PVE7.1 just today and found the package version dialog background to be white which makes the text invisible unless marked.
I cleared the browser cache and used a private window to be sure it's not a cache issue.
![grafik](https://user-images.githubusercontent.com/10433914/142212063-e05cbae6-ec9b-47e1-8050-05f160c1a307.png)

**Comment by DOWIT-JoelFrojmowicz** [comment]
Hi, when I upgraded my Proxmox to latest version (7.1), the dark theme was disabled and the theme returned to default.
Running "bash PVEDiscordDark.sh install" again solve the problem. 

But my question is: Is possible to maintain the theme after upgrades?

**Comment by djraw** [comment]
I'm sorry, but that should be another issue, added to the readme or a wiki page. It has nothing to do with my issue. After the PVE7.1 upgrade I reinstalled the theme just as you did.

> But my question is: Is possible to maintain the theme after upgrades?

No, not from within the script. Whenever the pve-manager package gets upgraded, the changes made by the script are overwritten by the new version. So you need to run it again.

It might be possible to add the execution as a hook (google please ;)), but honestly I prefer to use the script with the status function after upgrades and reinstall if needed.

**Comment by Zackptg5** [comment]
@DOWIT-JoelFrojmowicz As seen with this original issue, updates may (and often do) break parts of theme modifications such as this one so automatic update would be automatic breaking which would not be preferred by most people

**Comment by Weilbyte** [comment]
Thanks for pointing this out, will need to update the patcher soon to cover it :)

And @DOWIT-JoelFrojmowicz, you need to reinstall it because apt overwrites the HTML template file (where the CSS and JS are appended) when the PVE package is updated. As pointed out, you can use apt hooks to run a simple script that checks the theme status and installs it if not installed.
